### ISSUE TITLE
Doesn't work on 3.70 Trinity

### ISSUE THREAD

**Issue by JarrahWhite** [theheroGAC/TF-Card-Plugin-Tool#2]
OK. I just installed firmware 3.70 on my Vita2000 and my PSTV and got Trinity up and running on both systems. For whatever though, my Vita won't detect my SD2Vita anymore. I usually use the TF Card Plugin Tool to switch it back and forth between uma0 and ux0. But now whenever I try to use the tool, the SD2Vita still isn't showing up. Even if I try to boot the SD2Vita as ux0, it just reboots the console with the memory card still as ux0. Does this plugin need to be updated to work on 3.70?

**Comment by Arutosio** [comment]
up

**Comment by theheroGAC** [comment]
now work on 3.69 and 3.70 https://github.com/theheroGAC/TF-Card-Plugin-Tool/releases/tag/2.24
