### ISSUE TITLE
StorageMgr credits missing

### ISSUE THREAD

**Issue by CelesteBlue-dev** [theheroGAC/TF-Card-Plugin-Tool#3]
Credits available here:
https://github.com/CelesteBlue-dev/PSVita-StorageMgr/blob/master/README.md#Credits

**Comment by theheroGAC** [comment]
ops sorry

**Comment by theheroGAC** [comment]
fixed https://github.com/theheroGAC/TF-Card-Plugin-Tool/blob/master/README.md
